name: Bypass jekyll build

on:
  workflow_run:
    workflows:
      - Deploy docs
    types:
      - completed
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: gh-pages
            fetch-depth: 0

        - name: Bypassing GitHub Pages Jekyll build
          run: touch .nojekyll

        - name: Commit changes
          run: |
            git config --global user.name 'GitHub Action'
            git config --global user.email '
            git add .
            git commit -m "Bypassing GitHub Pages Jekyll build"
            git push
