name: Deploy docs

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Setup pnpm
        with:
          version: 8
          cache: 'pnpm'

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: pnpm i --frozen-lockfile

      - run: pnpm run turbo:build

      - name: Deploy StoryBook
        working-directory: ./packages/docs
        run: pnpm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/docs/storybook-static