name: Deploy docs

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Setup pnpm
        with:
          version: 8

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - run: pnpm i --frozen-lockfile

      - run: pnpm run turbo:build
        env:
          TURBO_TOKEN: BHEVoi3dEkDlQj9YOagi5L6P
          TURBO_TEAM: pedrovs3

      - name: Deploy StoryBook
        working-directory: ./packages/docs
        run: pnpm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}